/**
 * Base de Datos Oficial PARLEY STATS PRO - Sincronizador Autónomo v5.0.0
 * Generado automáticamente: 2026-09-11 13:06:12 UTC
 */

export const TOP_PICKS_OF_THE_DAY = [
  {
    "id": "soc-italia-mon",
    "sport": "soccer",
    "sportName": "Fútbol",
    "sportIcon": "⚽",
    "league": "UEFA Nations League",
    "match": "Israel vs Italia",
    "gameDate": "Lunes 07 Sep",
    "gameTime": "2:45 PM (Hora VE)",
    "isoStartTime": "2026-09-07T14:45:00-04:00",
    "keyDetail": "Bozsik Aréna (Budapest - Cancha Neutral)",
    "selection": "Italia a Ganar",
    "decimalOdds": 1.3,
    "americanOdds": "-333",
    "estimatedProb": 0.84,
    "category": "seguro",
    "categoryLabel": "💎 Banquero Fútbol Lunes (2:45 PM)",
    "stars": 5,
    "edgePercent": "+9.2%",
    "confidenceScore": 96,
    "reasoning": "La Azzurra de Spalletti tras vencer a Francia 3-1 en París en su mejor momento. Duelo en sede neutral en Budapest donde Israel no tiene ventaja de campo.",
    "analysis": {
      "type": "soccer",
      "teamFavorite": {
        "name": "Italia (Favorito)",
        "xg": "2.35",
        "goalsAvg": "2.4 p/p",
        "streak": "G-P-E-G-G",
        "cleanSheetProb": "60%"
      },
      "teamUnderdog": {
        "name": "Israel (Rival)",
        "xg": "0.75",
        "goalsAvg": "0.8 p/p",
        "streak": "P-P-G-P-P",
        "cleanSheetProb": "8%"
      },
      "keyFactors": "Italia con la moral alta tras ganar en París. Mateo Retegui y Frattesi en racha goleadora.",
      "fairOdds": 1.19,
      "marketOdds": 1.3,
      "evPercent": "+9.2%",
      "riskLevel": "Bajo (🟢 Base Multideporte)",
      "recommendation": "Excelente base de alta probabilidad para sellar en parley."
    }
  },
  {
    "id": "mlb-api-823498",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "New York Mets vs New York Yankees",
    "gameDate": "Hoy",
    "gameTime": "07:05 PM (Hora VE)",
    "isoStartTime": "2026-09-11T19:05:00+00:00",
    "keyDetail": "Nolan McLean vs Carlos Rodón",
    "selection": "New York Yankees a Ganar (Carlos Rodón)",
    "decimalOdds": 1.48,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (07:05 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "New York Yankees de local con Carlos Rodón en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a New York Mets.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Carlos Rodón (NEW)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Nolan McLean (NEW)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.3,
      "marketOdds": 1.48,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre New York Yankees. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-823736",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Cincinnati Reds vs Milwaukee Brewers",
    "gameDate": "Hoy",
    "gameTime": "07:45 PM (Hora VE)",
    "isoStartTime": "2026-09-11T19:45:00+00:00",
    "keyDetail": "Andrew Abbott vs Dustin May",
    "selection": "Milwaukee Brewers a Ganar (Dustin May)",
    "decimalOdds": 1.48,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (07:45 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "Milwaukee Brewers de local con Dustin May en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Cincinnati Reds.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Dustin May (MIL)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Andrew Abbott (CIN)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.3,
      "marketOdds": 1.48,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Milwaukee Brewers. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-823496",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "New York Mets vs New York Yankees",
    "gameDate": "Mañana",
    "gameTime": "01:35 PM (Hora VE)",
    "isoStartTime": "2026-09-12T13:35:00+00:00",
    "keyDetail": "Zac Thornton vs Gerrit Cole",
    "selection": "New York Yankees a Ganar (Gerrit Cole)",
    "decimalOdds": 1.48,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (01:35 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "New York Yankees de local con Gerrit Cole en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a New York Mets.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Gerrit Cole (NEW)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Zac Thornton (NEW)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.3,
      "marketOdds": 1.48,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre New York Yankees. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-823737",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Cincinnati Reds vs Milwaukee Brewers",
    "gameDate": "Mañana",
    "gameTime": "07:10 PM (Hora VE)",
    "isoStartTime": "2026-09-12T19:10:00+00:00",
    "keyDetail": "Brady Singer vs Por Anunciar",
    "selection": "Milwaukee Brewers a Ganar (Por Anunciar)",
    "decimalOdds": 1.48,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (07:10 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "Milwaukee Brewers de local con Por Anunciar en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Cincinnati Reds.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Por Anunciar (MIL)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Brady Singer (CIN)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.3,
      "marketOdds": 1.48,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Milwaukee Brewers. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "soc-francia-mon",
    "sport": "soccer",
    "sportName": "Fútbol",
    "sportIcon": "⚽",
    "league": "UEFA Nations League",
    "match": "Francia vs Bélgica",
    "gameDate": "Lunes 07 Sep",
    "gameTime": "2:45 PM (Hora VE)",
    "isoStartTime": "2026-09-07T14:45:00-04:00",
    "keyDetail": "Groupama Stadium (Lyon)",
    "selection": "Francia a Ganar",
    "decimalOdds": 1.72,
    "americanOdds": "-139",
    "estimatedProb": 0.69,
    "category": "valor",
    "categoryLabel": "🚀 Duelo Élite Europa (2:45 PM)",
    "stars": 5,
    "edgePercent": "+11.2%",
    "confidenceScore": 92,
    "reasoning": "Kylian Mbappé, Ousmane Dembélé y Antoine Griezmann en Lyon. Bélgica llega sin Romelu Lukaku y con serios problemas defensivos.",
    "analysis": {
      "type": "soccer",
      "teamFavorite": {
        "name": "Francia (Local)",
        "xg": "2.10",
        "goalsAvg": "2.3 p/p",
        "streak": "G-G-P-G-G",
        "cleanSheetProb": "55%"
      },
      "teamUnderdog": {
        "name": "Bélgica (Visitante)",
        "xg": "1.05",
        "goalsAvg": "1.2 p/p",
        "streak": "P-E-G-P-P",
        "cleanSheetProb": "18%"
      },
      "keyFactors": "Superioridad física y velocidad en transiciones de Mbappé frente a centrales de Bélgica.",
      "fairOdds": 1.45,
      "marketOdds": 1.72,
      "evPercent": "+11.2%",
      "riskLevel": "Medio-Bajo (🟡 Gran Cuota +EV)",
      "recommendation": "Francia domina el historial directo y tiene plantel superior en todas las líneas."
    }
  },
  {
    "id": "mlb-api-824631",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Pittsburgh Pirates vs Chicago Cubs",
    "gameDate": "Hoy",
    "gameTime": "02:20 PM (Hora VE)",
    "isoStartTime": "2026-09-11T14:20:00+00:00",
    "keyDetail": "Wilber Dotel vs Shota Imanaga",
    "selection": "Chicago Cubs a Ganar (Shota Imanaga)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (02:20 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Chicago Cubs de local con Shota Imanaga en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Pittsburgh Pirates.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Shota Imanaga (CHI)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Wilber Dotel (PIT)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Chicago Cubs. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-824227",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Colorado Rockies vs Detroit Tigers",
    "gameDate": "Hoy",
    "gameTime": "06:40 PM (Hora VE)",
    "isoStartTime": "2026-09-11T18:40:00+00:00",
    "keyDetail": "Mason Adams vs Framber Valdez",
    "selection": "Detroit Tigers a Ganar (Framber Valdez)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (06:40 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Detroit Tigers de local con Framber Valdez en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Colorado Rockies.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Framber Valdez (DET)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Mason Adams (COL)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Detroit Tigers. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-822684",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Los Angeles Angels vs Washington Nationals",
    "gameDate": "Hoy",
    "gameTime": "06:45 PM (Hora VE)",
    "isoStartTime": "2026-09-11T18:45:00+00:00",
    "keyDetail": "Yusei Kikuchi vs Cade Cavalli",
    "selection": "Washington Nationals a Ganar (Cade Cavalli)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (06:45 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Washington Nationals de local con Cade Cavalli en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Los Angeles Angels.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Cade Cavalli (WAS)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Yusei Kikuchi (LOS)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Washington Nationals. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-822767",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Baltimore Orioles vs Toronto Blue Jays",
    "gameDate": "Hoy",
    "gameTime": "07:07 PM (Hora VE)",
    "isoStartTime": "2026-09-11T19:07:00+00:00",
    "keyDetail": "Chris Bassitt vs Max Scherzer",
    "selection": "Toronto Blue Jays a Ganar (Max Scherzer)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (07:07 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Toronto Blue Jays de local con Max Scherzer en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Baltimore Orioles.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Max Scherzer (TOR)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Chris Bassitt (BAL)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Toronto Blue Jays. Duelo favorable de abridores y respaldo en casa."
    }
  }
];

export const SPORTS_DATA = {
  baseball: { name: "Béisbol (MLB)", leagues: ["MLB Lunes Tarde/Noche"] },
  soccer: { name: "Fútbol", leagues: ["UEFA Nations League"] }
};
