/**
 * Base de Datos Oficial PARLEY STATS PRO - Sincronizador Autónomo v5.0.0
 * Generado automáticamente: 2026-09-30 14:18:15 UTC
 */

export const TOP_PICKS_OF_THE_DAY = [
  {
    "id": "soc-italia-mon",
    "sport": "soccer",
    "sportName": "Fútbol",
    "sportIcon": "⚽",
    "league": "UEFA Nations League",
    "match": "Israel vs Italia",
    "gameDate": "Lunes 07 Sep",
    "gameTime": "2:45 PM (Hora VE)",
    "isoStartTime": "2026-09-07T14:45:00-04:00",
    "keyDetail": "Bozsik Aréna (Budapest - Cancha Neutral)",
    "selection": "Italia a Ganar",
    "decimalOdds": 1.3,
    "americanOdds": "-333",
    "estimatedProb": 0.84,
    "category": "seguro",
    "categoryLabel": "💎 Banquero Fútbol Lunes (2:45 PM)",
    "stars": 5,
    "edgePercent": "+9.2%",
    "confidenceScore": 96,
    "reasoning": "La Azzurra de Spalletti tras vencer a Francia 3-1 en París en su mejor momento. Duelo en sede neutral en Budapest donde Israel no tiene ventaja de campo.",
    "analysis": {
      "type": "soccer",
      "teamFavorite": {
        "name": "Italia (Favorito)",
        "xg": "2.35",
        "goalsAvg": "2.4 p/p",
        "streak": "G-P-E-G-G",
        "cleanSheetProb": "60%"
      },
      "teamUnderdog": {
        "name": "Israel (Rival)",
        "xg": "0.75",
        "goalsAvg": "0.8 p/p",
        "streak": "P-P-G-P-P",
        "cleanSheetProb": "8%"
      },
      "keyFactors": "Italia con la moral alta tras ganar en París. Mateo Retegui y Frattesi en racha goleadora.",
      "fairOdds": 1.19,
      "marketOdds": 1.3,
      "evPercent": "+9.2%",
      "riskLevel": "Bajo (🟢 Base Multideporte)",
      "recommendation": "Excelente base de alta probabilidad para sellar en parley."
    }
  },
  {
    "id": "mlb-api-849848",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Boston Red Sox vs New York Yankees",
    "gameDate": "Hoy",
    "gameTime": "08:00 PM (Hora VE)",
    "isoStartTime": "2026-09-30T20:00:00+00:00",
    "keyDetail": "Sonny Gray vs Max Fried",
    "selection": "New York Yankees a Ganar (Max Fried)",
    "decimalOdds": 1.75,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (08:00 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "New York Yankees de local con Max Fried en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Boston Red Sox.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Max Fried (NEW)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Sonny Gray (BOS)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.54,
      "marketOdds": 1.75,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre New York Yankees. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-849842",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Chicago Cubs vs San Diego Padres",
    "gameDate": "Hoy",
    "gameTime": "10:00 PM (Hora VE)",
    "isoStartTime": "2026-09-30T22:00:00+00:00",
    "keyDetail": "Kevin Gausman vs Nick Pivetta",
    "selection": "San Diego Padres a Ganar (Nick Pivetta)",
    "decimalOdds": 1.75,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (10:00 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "San Diego Padres de local con Nick Pivetta en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Chicago Cubs.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Nick Pivetta (SAN)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Kevin Gausman (CHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.54,
      "marketOdds": 1.75,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre San Diego Padres. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-849847",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Boston Red Sox vs New York Yankees",
    "gameDate": "Mañana",
    "gameTime": "08:00 PM (Hora VE)",
    "isoStartTime": "2026-10-01T20:00:00+00:00",
    "keyDetail": "Ranger Suarez vs Gerrit Cole",
    "selection": "New York Yankees a Ganar (Gerrit Cole)",
    "decimalOdds": 1.75,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (08:00 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "New York Yankees de local con Gerrit Cole en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Boston Red Sox.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Gerrit Cole (NEW)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Ranger Suarez (BOS)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.54,
      "marketOdds": 1.75,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre New York Yankees. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-849840",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Chicago Cubs vs San Diego Padres",
    "gameDate": "Mañana",
    "gameTime": "10:00 PM (Hora VE)",
    "isoStartTime": "2026-10-01T22:00:00+00:00",
    "keyDetail": "Por Anunciar vs Por Anunciar",
    "selection": "San Diego Padres a Ganar (Por Anunciar)",
    "decimalOdds": 1.75,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (10:00 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "San Diego Padres de local con Por Anunciar en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Chicago Cubs.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Por Anunciar (SAN)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Por Anunciar (CHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.54,
      "marketOdds": 1.75,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre San Diego Padres. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "soc-francia-mon",
    "sport": "soccer",
    "sportName": "Fútbol",
    "sportIcon": "⚽",
    "league": "UEFA Nations League",
    "match": "Francia vs Bélgica",
    "gameDate": "Lunes 07 Sep",
    "gameTime": "2:45 PM (Hora VE)",
    "isoStartTime": "2026-09-07T14:45:00-04:00",
    "keyDetail": "Groupama Stadium (Lyon)",
    "selection": "Francia a Ganar",
    "decimalOdds": 1.72,
    "americanOdds": "-139",
    "estimatedProb": 0.69,
    "category": "valor",
    "categoryLabel": "🚀 Duelo Élite Europa (2:45 PM)",
    "stars": 5,
    "edgePercent": "+11.2%",
    "confidenceScore": 92,
    "reasoning": "Kylian Mbappé, Ousmane Dembélé y Antoine Griezmann en Lyon. Bélgica llega sin Romelu Lukaku y con serios problemas defensivos.",
    "analysis": {
      "type": "soccer",
      "teamFavorite": {
        "name": "Francia (Local)",
        "xg": "2.10",
        "goalsAvg": "2.3 p/p",
        "streak": "G-G-P-G-G",
        "cleanSheetProb": "55%"
      },
      "teamUnderdog": {
        "name": "Bélgica (Visitante)",
        "xg": "1.05",
        "goalsAvg": "1.2 p/p",
        "streak": "P-E-G-P-P",
        "cleanSheetProb": "18%"
      },
      "keyFactors": "Superioridad física y velocidad en transiciones de Mbappé frente a centrales de Bélgica.",
      "fairOdds": 1.45,
      "marketOdds": 1.72,
      "evPercent": "+11.2%",
      "riskLevel": "Medio-Bajo (🟡 Gran Cuota +EV)",
      "recommendation": "Francia domina el historial directo y tiene plantel superior en todas las líneas."
    }
  },
  {
    "id": "mlb-api-849841",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Philadelphia Phillies vs Atlanta Braves",
    "gameDate": "Hoy",
    "gameTime": "02:00 PM (Hora VE)",
    "isoStartTime": "2026-09-30T14:00:00+00:00",
    "keyDetail": "Cristopher Sánchez vs Tyler Mahle",
    "selection": "Atlanta Braves a Ganar (Tyler Mahle)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (02:00 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Atlanta Braves de local con Tyler Mahle en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Philadelphia Phillies.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Tyler Mahle (ATL)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Cristopher Sánchez (PHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Atlanta Braves. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-849846",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Chicago White Sox vs Houston Astros",
    "gameDate": "Hoy",
    "gameTime": "05:00 PM (Hora VE)",
    "isoStartTime": "2026-09-30T17:00:00+00:00",
    "keyDetail": "Sean Burke vs Hunter Brown",
    "selection": "Houston Astros a Ganar (Hunter Brown)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (05:00 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Houston Astros de local con Hunter Brown en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Chicago White Sox.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Hunter Brown (HOU)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Sean Burke (CHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Houston Astros. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-849844",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Philadelphia Phillies vs Atlanta Braves",
    "gameDate": "Mañana",
    "gameTime": "02:00 PM (Hora VE)",
    "isoStartTime": "2026-10-01T14:00:00+00:00",
    "keyDetail": "Por Anunciar vs Por Anunciar",
    "selection": "Atlanta Braves a Ganar (Por Anunciar)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (02:00 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Atlanta Braves de local con Por Anunciar en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Philadelphia Phillies.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Por Anunciar (ATL)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Por Anunciar (PHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Atlanta Braves. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-849850",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Chicago White Sox vs Houston Astros",
    "gameDate": "Mañana",
    "gameTime": "05:00 PM (Hora VE)",
    "isoStartTime": "2026-10-01T17:00:00+00:00",
    "keyDetail": "Por Anunciar vs Por Anunciar",
    "selection": "Houston Astros a Ganar (Por Anunciar)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (05:00 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Houston Astros de local con Por Anunciar en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Chicago White Sox.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Por Anunciar (HOU)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Por Anunciar (CHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Houston Astros. Duelo favorable de abridores y respaldo en casa."
    }
  }
];

export const SPORTS_DATA = {
  baseball: { name: "Béisbol (MLB)", leagues: ["MLB Lunes Tarde/Noche"] },
  soccer: { name: "Fútbol", leagues: ["UEFA Nations League"] }
};
