/**
 * Base de Datos Oficial PARLEY STATS PRO - Sincronizador Autónomo v5.0.0
 * Generado automáticamente: 2026-09-15 03:34:00 UTC
 */

export const TOP_PICKS_OF_THE_DAY = [
  {
    "id": "soc-italia-mon",
    "sport": "soccer",
    "sportName": "Fútbol",
    "sportIcon": "⚽",
    "league": "UEFA Nations League",
    "match": "Israel vs Italia",
    "gameDate": "Lunes 07 Sep",
    "gameTime": "2:45 PM (Hora VE)",
    "isoStartTime": "2026-09-07T14:45:00-04:00",
    "keyDetail": "Bozsik Aréna (Budapest - Cancha Neutral)",
    "selection": "Italia a Ganar",
    "decimalOdds": 1.3,
    "americanOdds": "-333",
    "estimatedProb": 0.84,
    "category": "seguro",
    "categoryLabel": "💎 Banquero Fútbol Lunes (2:45 PM)",
    "stars": 5,
    "edgePercent": "+9.2%",
    "confidenceScore": 96,
    "reasoning": "La Azzurra de Spalletti tras vencer a Francia 3-1 en París en su mejor momento. Duelo en sede neutral en Budapest donde Israel no tiene ventaja de campo.",
    "analysis": {
      "type": "soccer",
      "teamFavorite": {
        "name": "Italia (Favorito)",
        "xg": "2.35",
        "goalsAvg": "2.4 p/p",
        "streak": "G-P-E-G-G",
        "cleanSheetProb": "60%"
      },
      "teamUnderdog": {
        "name": "Israel (Rival)",
        "xg": "0.75",
        "goalsAvg": "0.8 p/p",
        "streak": "P-P-G-P-P",
        "cleanSheetProb": "8%"
      },
      "keyFactors": "Italia con la moral alta tras ganar en París. Mateo Retegui y Frattesi en racha goleadora.",
      "fairOdds": 1.19,
      "marketOdds": 1.3,
      "evPercent": "+9.2%",
      "riskLevel": "Bajo (🟢 Base Multideporte)",
      "recommendation": "Excelente base de alta probabilidad para sellar en parley."
    }
  },
  {
    "id": "mlb-api-824384",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Chicago White Sox vs Cleveland Guardians",
    "gameDate": "Mañana",
    "gameTime": "06:40 PM (Hora VE)",
    "isoStartTime": "2026-09-15T18:40:00+00:00",
    "keyDetail": "Davis Martin vs Foster Griffin",
    "selection": "Cleveland Guardians a Ganar (Foster Griffin)",
    "decimalOdds": 1.48,
    "americanOdds": "-208",
    "estimatedProb": 0.77,
    "category": "seguro",
    "categoryLabel": "💎 Banquero (06:40 PM)",
    "stars": 5,
    "edgePercent": "+10.8%",
    "confidenceScore": 95,
    "reasoning": "Cleveland Guardians de local con Foster Griffin en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Chicago White Sox.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Foster Griffin (CLE)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Davis Martin (CHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.3,
      "marketOdds": 1.48,
      "evPercent": "+10.8%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Cleveland Guardians. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "soc-francia-mon",
    "sport": "soccer",
    "sportName": "Fútbol",
    "sportIcon": "⚽",
    "league": "UEFA Nations League",
    "match": "Francia vs Bélgica",
    "gameDate": "Lunes 07 Sep",
    "gameTime": "2:45 PM (Hora VE)",
    "isoStartTime": "2026-09-07T14:45:00-04:00",
    "keyDetail": "Groupama Stadium (Lyon)",
    "selection": "Francia a Ganar",
    "decimalOdds": 1.72,
    "americanOdds": "-139",
    "estimatedProb": 0.69,
    "category": "valor",
    "categoryLabel": "🚀 Duelo Élite Europa (2:45 PM)",
    "stars": 5,
    "edgePercent": "+11.2%",
    "confidenceScore": 92,
    "reasoning": "Kylian Mbappé, Ousmane Dembélé y Antoine Griezmann en Lyon. Bélgica llega sin Romelu Lukaku y con serios problemas defensivos.",
    "analysis": {
      "type": "soccer",
      "teamFavorite": {
        "name": "Francia (Local)",
        "xg": "2.10",
        "goalsAvg": "2.3 p/p",
        "streak": "G-G-P-G-G",
        "cleanSheetProb": "55%"
      },
      "teamUnderdog": {
        "name": "Bélgica (Visitante)",
        "xg": "1.05",
        "goalsAvg": "1.2 p/p",
        "streak": "P-E-G-P-P",
        "cleanSheetProb": "18%"
      },
      "keyFactors": "Superioridad física y velocidad en transiciones de Mbappé frente a centrales de Bélgica.",
      "fairOdds": 1.45,
      "marketOdds": 1.72,
      "evPercent": "+11.2%",
      "riskLevel": "Medio-Bajo (🟡 Gran Cuota +EV)",
      "recommendation": "Francia domina el historial directo y tiene plantel superior en todas las líneas."
    }
  },
  {
    "id": "mlb-api-824308",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "San Diego Padres vs Colorado Rockies",
    "gameDate": "Hoy",
    "gameTime": "08:40 PM (Hora VE)",
    "isoStartTime": "2026-09-14T20:40:00+00:00",
    "keyDetail": "Casey Mize vs Tomoyuki Sugano",
    "selection": "Colorado Rockies a Ganar (Tomoyuki Sugano)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (08:40 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Colorado Rockies de local con Tomoyuki Sugano en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a San Diego Padres.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Tomoyuki Sugano (COL)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Casey Mize (SAN)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Colorado Rockies. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-823981",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Seattle Mariners vs Los Angeles Angels",
    "gameDate": "Hoy",
    "gameTime": "09:38 PM (Hora VE)",
    "isoStartTime": "2026-09-14T21:38:00+00:00",
    "keyDetail": "Kade Anderson vs Reid Detmers",
    "selection": "Los Angeles Angels a Ganar (Reid Detmers)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (09:38 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Los Angeles Angels de local con Reid Detmers en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Seattle Mariners.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Reid Detmers (LOS)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Kade Anderson (SEA)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Los Angeles Angels. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-825034",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Hoy)",
    "match": "Miami Marlins vs Arizona Diamondbacks",
    "gameDate": "Hoy",
    "gameTime": "09:40 PM (Hora VE)",
    "isoStartTime": "2026-09-14T21:40:00+00:00",
    "keyDetail": "Sandy Alcantara vs Corbin Burnes",
    "selection": "Arizona Diamondbacks a Ganar (Corbin Burnes)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (09:40 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Arizona Diamondbacks de local con Corbin Burnes en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Miami Marlins.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Corbin Burnes (ARI)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Sandy Alcantara (MIA)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Arizona Diamondbacks. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-824466",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Los Angeles Dodgers vs Cincinnati Reds",
    "gameDate": "Mañana",
    "gameTime": "06:40 PM (Hora VE)",
    "isoStartTime": "2026-09-15T18:40:00+00:00",
    "keyDetail": "Yoshinobu Yamamoto vs Rhett Lowder",
    "selection": "Cincinnati Reds a Ganar (Rhett Lowder)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (06:40 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Cincinnati Reds de local con Rhett Lowder en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Los Angeles Dodgers.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Rhett Lowder (CIN)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Yoshinobu Yamamoto (LOS)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Cincinnati Reds. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-822925",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Athletics vs Tampa Bay Rays",
    "gameDate": "Mañana",
    "gameTime": "06:40 PM (Hora VE)",
    "isoStartTime": "2026-09-15T18:40:00+00:00",
    "keyDetail": "Jack Perkins vs Griffin Jax",
    "selection": "Tampa Bay Rays a Ganar (Griffin Jax)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (06:40 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Tampa Bay Rays de local con Griffin Jax en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Athletics.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Griffin Jax (TAM)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Jack Perkins (ATH)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Tampa Bay Rays. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-823333",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Milwaukee Brewers vs Pittsburgh Pirates",
    "gameDate": "Mañana",
    "gameTime": "06:40 PM (Hora VE)",
    "isoStartTime": "2026-09-15T18:40:00+00:00",
    "keyDetail": "Jacob Misiorowski vs Lake Bachar",
    "selection": "Pittsburgh Pirates a Ganar (Lake Bachar)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (06:40 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Pittsburgh Pirates de local con Lake Bachar en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Milwaukee Brewers.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Lake Bachar (PIT)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Jacob Misiorowski (MIL)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Pittsburgh Pirates. Duelo favorable de abridores y respaldo en casa."
    }
  },
  {
    "id": "mlb-api-822683",
    "sport": "baseball",
    "sportName": "MLB",
    "sportIcon": "⚾",
    "league": "MLB (Mañana)",
    "match": "Philadelphia Phillies vs Washington Nationals",
    "gameDate": "Mañana",
    "gameTime": "06:45 PM (Hora VE)",
    "isoStartTime": "2026-09-15T18:45:00+00:00",
    "keyDetail": "Cristopher Sánchez vs Jackson Kent",
    "selection": "Washington Nationals a Ganar (Jackson Kent)",
    "decimalOdds": 1.62,
    "americanOdds": "-161",
    "estimatedProb": 0.7,
    "category": "valor",
    "categoryLabel": "🚀 Alto Valor +EV (06:45 PM)",
    "stars": 4,
    "edgePercent": "+9.5%",
    "confidenceScore": 90,
    "reasoning": "Washington Nationals de local con Jackson Kent en la lomita. Ventaja de pitcheo y mayor producción de carreras en su estadio frente a Philadelphia Phillies.",
    "analysis": {
      "type": "baseball",
      "starterFavorite": {
        "name": "Jackson Kent (WAS)",
        "era": "3.35",
        "whip": "1.08",
        "k9": "9.5",
        "record": "10-6",
        "form": "2.40 ERA en aperturas recientes"
      },
      "starterUnderdog": {
        "name": "Cristopher Sánchez (PHI)",
        "era": "4.60",
        "whip": "1.36",
        "k9": "7.8",
        "record": "4-8",
        "form": "Vulnerable fuera de casa"
      },
      "bullpenFavEra": "3.30",
      "bullpenDogEra": "4.50",
      "offenseFav": "4.9 carreras/juego de local",
      "offenseDog": "3.8 carreras/juego",
      "fairOdds": 1.43,
      "marketOdds": 1.62,
      "evPercent": "+9.5%",
      "riskLevel": "Bajo (🟢 Sólido)",
      "recommendation": "Apuesta con ventaja matemática sobre Washington Nationals. Duelo favorable de abridores y respaldo en casa."
    }
  }
];

export const SPORTS_DATA = {
  baseball: { name: "Béisbol (MLB)", leagues: ["MLB Lunes Tarde/Noche"] },
  soccer: { name: "Fútbol", leagues: ["UEFA Nations League"] }
};
